import { Routes } from '@angular/router';
import { LoginClientComponent } from './components/auth/login-client/login-client.component';
import { LoginBoutiqueComponent } from './components/auth/login-boutique/login-boutique.component';
import { LoginAdminComponent } from './components/auth/login-admin/login-admin.component';
import { ClientDashboardComponent } from './components/client/client-dashboard/client-dashboard.component';
import { BoutiqueDashboardComponent } from './components/boutique/boutique-dashboard/boutique-dashboard.component';
import { AdminDashboardComponent } from './components/admin/admin-dashboard/admin-dashboard.component';
import { BoutiqueProduitsComponent } from './components/boutique/boutique-produits/boutique-produits.component';
import { ProduitFormComponent } from './components/boutique/produit-form/produit-form.component';
import { ProduitDetailsComponent } from './components/boutique/produit-details/produit-details.component';
import { BoutiquePanierComponent } from './components/boutique/boutique-panier/boutique-panier.component';
import { CommandeClientListeComponent } from './components/boutique/commande-client-liste/commande-client-liste.component';
import { BoutiqueLoyersComponent } from './components/boutique/boutique-loyers/boutique-loyers.component';
import { ClientCatalogueProduitComponent } from './components/client/client-catalogue-produit/client-catalogue-produit.component';
import { ClientPanierComponent } from './components/client/client-panier/client-panier.component';
import { ClientCommandeComponent } from './components/client/client-commande/client-commande.component';
import { ClientProduitDetailsComponent } from './components/client/client-produit-details/client-produit-details.component';
export const routes: Routes = [
  { path: 'commande-client-liste', component: CommandeClientListeComponent },
  { path: 'login-client', component: LoginClientComponent },
  { path: 'boutique-loyers', component: BoutiqueLoyersComponent },
  { path: 'login-boutique', component: LoginBoutiqueComponent },
  { path: 'login-admin', component: LoginAdminComponent },
  { path: 'client-dashboard', component: ClientDashboardComponent },
  { path: 'boutique-dashboard', component: BoutiqueDashboardComponent },
  { path: 'admin-dashboard', component: AdminDashboardComponent },
  { path: 'boutique-produit', component: BoutiqueProduitsComponent },
  { path: 'produit-form', component: ProduitFormComponent },
  { path: 'panier-boutique', component: BoutiquePanierComponent },
  { path: 'client-panier', component: ClientPanierComponent },
  { path: 'client-commande', component: ClientCommandeComponent },
  { path: 'client-catalogue-produit/:id', component: ClientCatalogueProduitComponent },
  { path: 'produit-details/:id', component: ProduitDetailsComponent },
  { path: 'client-produit-details/:id', component: ClientProduitDetailsComponent },
  { path: '', redirectTo: 'login-client', pathMatch: 'full' }
];